name: WebGameStats
version: 2.0.0
main: me.alexprogrammerde.WebPlayTime.Main
api-version: 1.16
authors: [Nate, Legault, AlexProgrammerDE]
description: Plugin to host Playtime website.
website: https://joindate.6b6t.org
depend: [Playtimes]